name: build-dokan-memfs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Dokany source
        uses: actions/checkout@v4
        with:
          repository: dokan-dev/dokany
          submodules: recursive
          path: dokany

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build dokan_memfs project
        shell: cmd
        run: |
          cd dokany
          msbuild samples\dokan_memfs\dokan_memfs.vcxproj ^
            /m ^
            /p:Configuration=Release ^
            /p:Platform=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dokan_memfs
          path: |
            dokany\**\dokan_memfs.exe
